name: Jekyll site CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # Choose the Ruby version that matches the GitHub Pages environment
          bundler-cache: true # Automatically run bundle install

      - name: Build and test Jekyll site
        run: |
          bundle exec jekyll build
          bundle exec jekyll doctor # Optional: Outputs any deprecation or configuration issues

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
